Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/game/int_handlers/dependent/dependent_ih.h File Reference
dependent_ih.h File Reference
#include <lcom/lcf.h>
#include "../../../drivers/kbc/kbc.h"
#include "../../../drivers/keyboard/kbd_keys.h"
#include "../../../drivers/mouse/mouse.h"
#include "../../protocol/communication_protocol.h"
#include "../../state_machine/menu_st.h"
#include "../../state_machine/mouse_st.h"
#include "../../views/font/font.h"
#include "../../views/sprite/sprite.h"
#include "../../views/views.h"
#include "../independent/independent_ih.h"
Functions
EVENTS handle_evt (EVENTS)
Handles Program Events.
EVENTS handle_timer_evt (EVENTS event)
Handles Timer Events.
EVENTS handle_kbd_evt (EVENTS event)
Handles KBD Events.
EVENTS handle_mouse_evt (EVENTS event)
Handles Mouse Events.
EVENTS handle_ser_evt (EVENTS events)
Handles Serial Port Events.
Variables
static bool move_right = false
static bool move_up = false
static bool move_down = false
static bool move_left = false
static unsigned char scan [2]
static int scan_size
static bool pendingMsg = false
static char user_msg [6][15]
static int row = 0
static enum state_codes cur_state = entry
static enum ret_codes rc
static int(* state_fun)(struct mouse_ev *event)
static enum Communication_Status com_status = no_one
static enum menu_ret_codes menu_rc
static int(* menu_state_fun)(struct mouse_ev *event, int x, int y)
static struct mouse_ev * m_event
Function Documentation
handle_evt()
EVENTS handle_evt (EVENTS event)
Handles Program Events.
Parameters
event Type of Event to Handle
Returns
0 on success
Definition at line 6 of file dependent_ih.c.
References handle_kbd_evt(), handle_mouse_evt(), handle_ser_evt(), handle_timer_evt(), KBD_EVT, MOUSE_EVT, NO_EVT, TIMER_EVT, and UART_EVT.
handle_kbd_evt()
EVENTS handle_kbd_evt (EVENTS event)
Handles KBD Events.
Parameters
event Type of Event to Handle
Returns
EVENTS
Definition at line 62 of file dependent_ih.c.
References BREAK_EVT, CHECKCall, COM1_ADDR, DOWN_ARROW, encode_protocol(), ESC_BREAK_CODE, game_set_state(), get_ascii_from_scancode(), get_can_move(), get_kbd_selected_opt(), get_menu_state(), kbc_get_error(), kbc_get_scancode(), kbc_ready(), LEFT_ARROW, menu_end, menu_lookup_transitions(), Protocol::message, move_down, move_left, move_right, move_up, NO_EVT, RELEASE_DOWN_ARROW, RELEASE_LEFT_ARROW, RELEASE_RIGHT_ARROW, RELEASE_UP_ARROW, RIGHT_ARROW, scan, scan_size, ser_writeb(), set_can_move(), set_kbd_selected_opt(), set_menu_state(), and UP_ARROW.
handle_mouse_evt()
EVENTS handle_mouse_evt (EVENTS event)
Handles Mouse Events.
Parameters
event Type of Event to Handle
Returns
EVENTS
Definition at line 130 of file dependent_ih.c.
References BREAK_EVT, COM1_ADDR, com_status, Protocol::com_status, connected, cur_state, encode_protocol(), free_board(), game_set_state(), get_can_move(), get_cursor_X(), get_cursor_Y(), get_menu_state(), kbc_get_error(), kbc_get_mouse_data(), kbc_mouse_ready(), lookup_transitions(), m_event, menu_end, menu_lookup_transitions(), menu_rc, menu_state, menu_state_fun, mouse_data_to_packet(), mouse_get_event(), mouse_update_pos(), multiplayer, NO_EVT, no_one, online, rc, scan, ser_writeb(), set_can_move(), set_connected(), set_menu_state(), set_online_color(), set_up_board(), state, state_fun, and waiting.
handle_ser_evt()
EVENTS handle_ser_evt (EVENTS events)
Handles Serial Port Events.
Parameters
event Type of Event to Handle
Returns
EVENTS
Definition at line 213 of file dependent_ih.c.
References COM1_ADDR, com_status, Protocol::com_status, connected, decode_protocol(), Protocol::dest, get_int_type(), Protocol::message, Protocol::more_chars, Protocol::move, move_piece_from_to(), NO_EVT, Protocol::origin, pendingMsg, RECEIVE_DATA, row, ser_readb(), set_can_move(), set_connected(), TX_EMPTY, and user_msg.
handle_timer_evt()
EVENTS handle_timer_evt (EVENTS event)
Handles Timer Events.
Parameters
event Type of Event to Handle
Returns
0 on success
Definition at line 25 of file dependent_ih.c.
References com_status, draw_text(), draw_update(), flush_screen(), get_menu_state(), NO_EVT, no_one, online, pendingMsg, user_msg, vg_draw_rectangle(), and waiting.
Variable Documentation
com_status
enum Communication_Status com_status = no_one static
Definition at line 29 of file dependent_ih.h.
cur_state
enum state_codes cur_state = entry static
Definition at line 25 of file dependent_ih.h.
m_event
struct mouse_ev* m_event static
Definition at line 34 of file dependent_ih.h.
menu_rc
enum menu_ret_codes menu_rc static
Definition at line 31 of file dependent_ih.h.
menu_state_fun
int(* menu_state_fun) (struct mouse_ev *event, int x, int y) (struct mouse_ev * event, int x, int y) static
Definition at line 32 of file dependent_ih.h.
move_down
bool move_down = false static
Definition at line 17 of file dependent_ih.h.
move_left
bool move_left = false static
Definition at line 17 of file dependent_ih.h.
move_right
bool move_right = false static
Definition at line 17 of file dependent_ih.h.
move_up
bool move_up = false static
Definition at line 17 of file dependent_ih.h.
pendingMsg
bool pendingMsg = false static
Definition at line 21 of file dependent_ih.h.
rc
enum ret_codes rc static
Definition at line 26 of file dependent_ih.h.
row
int row = 0 static
Definition at line 23 of file dependent_ih.h.
scan
unsigned char scan[2] static
Definition at line 18 of file dependent_ih.h.
scan_size
int scan_size static
Definition at line 19 of file dependent_ih.h.
state_fun
int(* state_fun) (struct mouse_ev *event) (struct mouse_ev * event) static
Definition at line 27 of file dependent_ih.h.
user_msg
char user_msg[6][15] static
Definition at line 22 of file dependent_ih.h.