Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/game/views/font/font.h File Reference
font.h File Reference
#include <lcom/lcf.h>
#include "../animation/animation.h"
#include "../sprite/sprite.h"
Functions
void draw_text (char *text, int x0, int y0, int hexColor, bool small)
Draws the given string in the given position The color must also be specifified and a boolean telling if font size is small or large.
char get_ascii_from_scancode (uint8_t scancode)
Get the ascii from scancode object.
Variables
static char kbd_US [128]
static sprite_t * a = NULL
static AnimSprite * f_small = NULL
Function Documentation
draw_text()
void draw_text (char * text, int x0, int y0, int hexColor, bool small)
Draws the given string in the given position The color must also be specifified and a boolean telling if font size is small or large.
Parameters
text text to be drawn
x0 start x position of the drawn string
y0 start y position of the drawn string
hexColor color the text should have
small boolean if text should be small
Definition at line 101 of file font.c.
References a, create_animSprite(), draw_animSprite(), draw_char(), f_small, letters, make_sprite(), and numbers.
get_ascii_from_scancode()
char get_ascii_from_scancode (uint8_t scancode)
Get the ascii from scancode object.
Parameters
scancode scancode where to get ascii frome
Returns
char ascii code retrieved
Definition at line 144 of file font.c.
References kbd_US, and scancode.
Variable Documentation
a
sprite_t* a = NULL static
Definition at line 11 of file font.h.
f_small
AnimSprite* f_small = NULL static
Definition at line 12 of file font.h.
kbd_US
char kbd_US[128] static
Definition at line 9 of file font.h.