Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/game/views/font/font.c File Reference
font.c File Reference
#include "font.h"
#include "../../../assets/font/char_065.xpm"
#include "../../../assets/font/char_066.xpm"
#include "../../../assets/font/char_067.xpm"
#include "../../../assets/font/char_068.xpm"
#include "../../../assets/font/char_069.xpm"
#include "../../../assets/font/char_070.xpm"
#include "../../../assets/font/char_071.xpm"
#include "../../../assets/font/char_072.xpm"
#include "../../../assets/font/char_073.xpm"
#include "../../../assets/font/char_074.xpm"
#include "../../../assets/font/char_075.xpm"
#include "../../../assets/font/char_076.xpm"
#include "../../../assets/font/char_077.xpm"
#include "../../../assets/font/char_078.xpm"
#include "../../../assets/font/char_079.xpm"
#include "../../../assets/font/char_080.xpm"
#include "../../../assets/font/char_081.xpm"
#include "../../../assets/font/char_082.xpm"
#include "../../../assets/font/char_083.xpm"
#include "../../../assets/font/char_084.xpm"
#include "../../../assets/font/char_085.xpm"
#include "../../../assets/font/char_086.xpm"
#include "../../../assets/font/char_087.xpm"
#include "../../../assets/font/char_088.xpm"
#include "../../../assets/font/char_089.xpm"
#include "../../../assets/font/char_090.xpm"
#include "../../../assets/font/char_048.xpm"
#include "../../../assets/font/char_049.xpm"
#include "../../../assets/font/char_050.xpm"
#include "../../../assets/font/char_051.xpm"
#include "../../../assets/font/char_052.xpm"
#include "../../../assets/font/char_053.xpm"
#include "../../../assets/font/char_054.xpm"
#include "../../../assets/font/char_055.xpm"
#include "../../../assets/font/char_056.xpm"
#include "../../../assets/font/char_057.xpm"
#include "../../../assets/font/char_032.xpm"
#include "../../../assets/font/char_033.xpm"
#include "../../../assets/font/char_035.xpm"
#include "../../../assets/font/char_047.xpm"
#include "../../../assets/font/char_058.xpm"
#include "../../../assets/font/char_063.xpm"
#include "../../../assets/fontbitmap.xpm"
Functions
void draw_char (xpm_map_t xpm, int x0, int y0, int hexColor)
void draw_text (char *text, int x0, int y0, int hexColor, bool small)
Draws the given string in the given position The color must also be specifified and a boolean telling if font size is small or large.
char get_ascii_from_scancode (uint8_t scancode)
Get the ascii from scancode object.
Variables
static xpm_map_t letters [] = {xpm_char_065, xpm_char_066, xpm_char_067, xpm_char_068, xpm_char_069, xpm_char_070, xpm_char_071, xpm_char_072, xpm_char_073, xpm_char_074, xpm_char_075, xpm_char_076, xpm_char_077, xpm_char_078, xpm_char_079, xpm_char_080, xpm_char_081, xpm_char_082, xpm_char_083, xpm_char_084, xpm_char_085, xpm_char_086, xpm_char_087, xpm_char_088, xpm_char_089, xpm_char_090}
static xpm_map_t numbers [] = {xpm_char_048, xpm_char_049, xpm_char_050, xpm_char_051, xpm_char_052, xpm_char_053, xpm_char_054, xpm_char_055, xpm_char_056, xpm_char_057}
static char kbd_US [128]
Function Documentation
draw_char()
void draw_char (xpm_map_t xpm, int x0, int y0, int hexColor)
Definition at line 93 of file font.c.
References draw_text_sprite(), free_sprite(), make_sprite(), set_sprite_X(), and set_sprite_Y().
draw_text()
void draw_text (char * text, int x0, int y0, int hexColor, bool small)
Draws the given string in the given position The color must also be specifified and a boolean telling if font size is small or large.
Parameters
text text to be drawn
x0 start x position of the drawn string
y0 start y position of the drawn string
hexColor color the text should have
small boolean if text should be small
Definition at line 101 of file font.c.
References a, create_animSprite(), draw_animSprite(), draw_char(), f_small, letters, make_sprite(), and numbers.
get_ascii_from_scancode()
char get_ascii_from_scancode (uint8_t scancode)
Get the ascii from scancode object.
Parameters
scancode scancode where to get ascii frome
Returns
char ascii code retrieved
Definition at line 144 of file font.c.
References kbd_US, and scancode.
Variable Documentation
kbd_US
char kbd_US[128] static
Initial value:
=
  {
    0, 27, '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '\b',
    '\t',
    'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '[', ']', '\n',
    0,
    'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ';', '\'', '`', 0, '\\', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', ',', '.', '/', 0,
    '*',
    0,
    ' ',
    0,
    0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0,
    0,
    0,
    0,
    0,
    0,
    '-',
    0,
    0,
    0,
    '+',
    0,
    0,
    0,
    0,
    0,
    0, 0, 0,
    0,
    0,
    0,
}
Definition at line 58 of file font.c.
letters
xpm_map_t letters[] = {xpm_char_065, xpm_char_066, xpm_char_067, xpm_char_068, xpm_char_069, xpm_char_070, xpm_char_071, xpm_char_072, xpm_char_073, xpm_char_074, xpm_char_075, xpm_char_076, xpm_char_077, xpm_char_078, xpm_char_079, xpm_char_080, xpm_char_081, xpm_char_082, xpm_char_083, xpm_char_084, xpm_char_085, xpm_char_086, xpm_char_087, xpm_char_088, xpm_char_089, xpm_char_090} static
Definition at line 31 of file font.c.
numbers
xpm_map_t numbers[] = {xpm_char_048, xpm_char_049, xpm_char_050, xpm_char_051, xpm_char_052, xpm_char_053, xpm_char_054, xpm_char_055, xpm_char_056, xpm_char_057} static
Definition at line 45 of file font.c.