Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/game/int_handlers/independent/independent_ih.c File Reference
independent_ih.c File Reference
#include "independent_ih.h"
Functions
void subscribe_ihs ()
Subscribes All Relevant Interrupts.
EVENTS handle_ihs ()
Handles All Relevant Interrupts.
void unsubscribe_ihs ()
Unsubscribes All Relevant Interrupts.
Function Documentation
handle_ihs()
EVENTS handle_ihs ()
Handles All Relevant Interrupts.
Returns
Type of event that took place
Definition at line 32 of file independent_ih.c.
References ipc_status, irq_mouse_set, irq_rtc, irq_ser, irq_set, irq_timer, kbc_ih(), KBD_EVT, MOUSE_EVT, mouse_ih(), msg, NO_EVT, r, RTC_EVT, rtc_ih(), TIMER_EVT, timer_int_handler(), UART_EVT, and uart_ih().
subscribe_ihs()
void subscribe_ihs ()
Subscribes All Relevant Interrupts.
Definition at line 3 of file independent_ih.c.
References _mouse_enable_data_reporting_(), CHECKCall, COM1_ADDR, IER_RECEIVED_INT, IER_RECEIVER_LINE_INT, IER_TRANSMITTER_INT, irq_mouse_set, irq_rtc, irq_ser, irq_set, irq_timer, kbc_hook_id, KBC_IRQ, kbc_mouse_hook_id, MOUSE_IRQ, rtc_subscribe_int(), ser_hook_id, ser_subscribe_int(), set_ier(), subscribe_kbc_interrupt(), timer_subscribe_int(), UART_RBR, and util_sys_inb().
unsubscribe_ihs()
void unsubscribe_ihs ()
Unsubscribes All Relevant Interrupts.
Definition at line 74 of file independent_ih.c.
References CHECKCall, COM1_ADDR, IER_RECEIVED_INT, IER_RECEIVER_LINE_INT, IER_TRANSMITTER_INT, kbc_hook_id, kbc_mouse_hook_id, mouse_disable_data_reporting(), rtc_unsubscribe_int(), ser_hook_id, set_ier(), timer_unsubscribe_int(), and unsubscribe_interrupt().