Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/drivers/keyboard/keyboard.h File Reference
keyboard.h File Reference
Kbd Api.
#include <lcom/lcf.h>
#include "../kbc/i8042.h"
#include "../kbc/kbc.h"
#include "../utils/handlers.h"
Functions
int() kbd_poll (uint8_t code[], uint8_t *size)
Reads Keyboard Scancode Bytes from the KBC Output Buffer.
int() kbd_restore ()
Sets bits 0 and 1 of the Output Buffer to 1.
int() kbc_kbd_interface_cmd ()
Tests the KBC Interface.
int() kbc_enable_kbd_cmd ()
Enables KBC Interface.
int() kbc_disable_kbd_cmd ()
Disables KBC Interface.
Detailed Description
Kbd Api.
Copyright
Copyright (c) 2022
Definition in file keyboard.h.
Function Documentation
kbc_disable_kbd_cmd()
int() kbc_disable_kbd_cmd ()
Disables KBC Interface.
Issue a kbc disable command.
Returns
EXIT_SUCCESS on success
Definition at line 39 of file keyboard.c.
References CHECKCall, KBC_INTERFACE_DISABLE, and kbc_issue_cmd().
kbc_enable_kbd_cmd()
int() kbc_enable_kbd_cmd ()
Enables KBC Interface.
Issue a kbc enable command.
Returns
EXIT_SUCCESS on success
Definition at line 33 of file keyboard.c.
References CHECKCall, KBC_INTERFACE_ENABLE, and kbc_issue_cmd().
kbc_kbd_interface_cmd()
int() kbc_kbd_interface_cmd ()
Tests the KBC Interface.
Returns
Status Byte Read from the Status Register
Definition at line 25 of file keyboard.c.
References CHECKCall, KBC_INTERFACE_TEST, kbc_issue_cmd(), kbc_read(), and state.
kbd_poll()
int() kbd_poll (uint8_t code[], uint8_t * size)
Reads Keyboard Scancode Bytes from the KBC Output Buffer.
Parameters
code[] Array where the Scancode Bytes are stored after reading
*size Size of the code[] array
Returns
EXIT_SUCCESS on success
Definition at line 6 of file keyboard.c.
References CHECKCall, kbc_read(), NullSafety, and TWO_BYTE_CODE.
kbd_restore()
int() kbd_restore ()
Sets bits 0 and 1 of the Output Buffer to 1.
Returns
EXIT_SUCCESS on success
Definition at line 45 of file keyboard.c.
References CHECKCall, INT_KBD, INT_MOUSE, kbc_read_cmd(), and kbc_write_cmd().