Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/game/objects/pieces.c File Reference
pieces.c File Reference
#include "pieces.h"
Functions
int get_square_color (uint16_t lin, uint16_t col)
Returns Color of Square in Pos (lin,col)
Piece_t * make_piece (AnimSprite *animSprite, PIECE_T p_t, Piece_Color color)
Creates a new Piece in the board.
void free_piece (Piece_t *p)
Frees Memory Allocated to a Piece.
void get_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8], bool isWhitesTurn)
Get the current valid moves for a specific piece.
bool valid_pawn_move (Board board[8][8], bool valid_moves[8][8], uint8_t lin, uint8_t col, uint8_t color)
Checks available moves for a pawn in the given board in the given position and updates the valid_moves matrix with the computed results.
void valid_pawn_eat (Board board[8][8], bool valid_moves[8][8], uint8_t lin, uint8_t col, uint8_t color)
Checks if (lin,col) contains an enemy piece, saving value in valid_moves.
void get_Pawn_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a Pawn in the given pos.
void get_Bishop_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a Bishop in the given pos.
void get_Queen_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a Queen in the given pos.
void valid_king_move (Board board[8][8], bool valid_moves[8][8], uint8_t lin, uint8_t col, uint8_t color)
Checks if a piece can be moved to (lin,col), saving value in valid_moves.
void get_King_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a King in the given pos.
void get_Rook_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a Rook in the given pos.
void valid_knight_move (Board board[8][8], bool valid_moves[8][8], uint8_t lin, uint8_t col, uint8_t color)
void get_Knight_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a Knight in the given pos.
bool isEnemyPiecePos (Piece_t *pos, int color)
Checks if there is an Enemy Piece in a certain position.
bool isOwnPiecePos (Piece_t *pos, int color)
Checks if there is an Ally Piece in a certain position.
bool is_inside_board (uint8_t lin, uint8_t col)
Checks if a certain position is inside the board.
Function Documentation
free_piece()
void free_piece (Piece_t * p)
Frees Memory Allocated to a Piece.
Parameters
p Piece whose memory we want to free
Definition at line 21 of file pieces.c.
get_Bishop_valid_moves()
void get_Bishop_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a Bishop in the given pos.
Parameters
board Board in its current state
lin Line where the Bishop is
col Column where the Bishop is
valid_moves Valid Moves matrix to be filled with the given piece valid moves where it is not
Definition at line 100 of file pieces.c.
References board, Piece::color, isEnemyPiecePos(), and isOwnPiecePos().
get_King_valid_moves()
void get_King_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a King in the given pos.
Parameters
board Board in its current state
lin Line where the King is
col Column where the King is
valid_moves Valid Moves matrix to be filled with the given piece valid moves where it is not
Definition at line 150 of file pieces.c.
References board, Piece::color, and valid_king_move().
get_Knight_valid_moves()
void get_Knight_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a Knight in the given pos.
Parameters
board Board in its current state
lin Line where the Knight is
col Column where the Knight is
valid_moves Valid Moves matrix to be filled with the given piece valid moves where it is not
Definition at line 210 of file pieces.c.
References board, Piece::color, and valid_knight_move().
get_Pawn_valid_moves()
void get_Pawn_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a Pawn in the given pos.
Parameters
board Board in its current state
lin Line where the Pawn is
col Column where the Pawn is
valid_moves Valid Moves matrix to be filled with the given piece valid moves where it is not
Definition at line 70 of file pieces.c.
References board, Piece::color, valid_pawn_eat(), valid_pawn_move(), and WHITE.
get_Queen_valid_moves()
void get_Queen_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a Queen in the given pos.
Parameters
board Board in its current state
lin Line where the Queen is
col Column where the Queen is
valid_moves Valid Moves matrix to be filled with the given piece valid moves where it is not
Definition at line 140 of file pieces.c.
References board, get_Bishop_valid_moves(), and get_Rook_valid_moves().
get_Rook_valid_moves()
void get_Rook_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8])
Get the current valid moves for a Rook in the given pos.
Parameters
board Board in its current state
lin Line where the Rook is
col Column where the Rook is
valid_moves Valid Moves matrix to be filled with the given piece valid moves where it is not
Definition at line 163 of file pieces.c.
References board, Piece::color, isEnemyPiecePos(), and isOwnPiecePos().
get_square_color()
int get_square_color (uint16_t lin, uint16_t col)
Returns Color of Square in Pos (lin,col)
Parameters
lin Line of the position
col Column of the position
Returns
0 if black
1 if white
Definition at line 3 of file pieces.c.
References BLACK, and WHITE.
get_valid_moves()
void get_valid_moves (Board board[8][8], uint8_t lin, uint8_t col, bool valid_moves[8][8], bool isWhitesTurn)
Get the current valid moves for a specific piece.
Parameters
board Board in its current state
lin Line where the piece is
col Column where the piece is
valid_moves Valid Moves matrix to be filled with the given piece valid moves where it is not
isWhitesTurn True if it's White turn or False if it's Black turn
Definition at line 26 of file pieces.c.
References Bishop, BLACK, board, BOARD_SIZE, get_Bishop_valid_moves(), get_King_valid_moves(), get_Knight_valid_moves(), get_Pawn_valid_moves(), get_Queen_valid_moves(), get_Rook_valid_moves(), isWhitesTurn, King, Knight, Pawn, Queen, Rook, and WHITE.
is_inside_board()
bool is_inside_board (uint8_t lin, uint8_t col)
Checks if a certain position is inside the board.
Parameters
lin Line of the position to Check
col Column of the position to check
Returns
true if position is inside the board
false if outside the board
Definition at line 231 of file pieces.c.
isEnemyPiecePos()
bool isEnemyPiecePos (Piece_t * pos, int color)
Checks if there is an Enemy Piece in a certain position.
Parameters
pos Position to Check
color Color of the Player from whomst perspective we want to check
Returns
true if piece is the opposite color
false if pos is empty or is a piece of the color of the player
Definition at line 223 of file pieces.c.
References Blank_space, Piece::color, and Piece::p_type.
isOwnPiecePos()
bool isOwnPiecePos (Piece_t * pos, int color)
Checks if there is an Ally Piece in a certain position.
Parameters
pos Position to Check
color Color of the Player from whomst perspective we want to check
Returns
true if piece is the same color
false if pos is empty or is a piece of the opposite
Definition at line 227 of file pieces.c.
References Blank_space, Piece::color, and Piece::p_type.
make_piece()
Piece_t * make_piece (AnimSprite * animSprite, PIECE_T p_t, Piece_Color color)
Creates a new Piece in the board.
Parameters
animSprite Sprite of the piece
p_t Struct where Piece Data will be Stored
color Piece Color
Returns
Piece_t* Piece Data
Definition at line 9 of file pieces.c.
References Piece::animSprite, Piece::color, and Piece::p_type.
valid_king_move()
void valid_king_move (Board board[8][8], bool valid_moves[8][8], uint8_t lin, uint8_t col, uint8_t color)
Checks if a piece can be moved to (lin,col), saving value in valid_moves.
Parameters
board Current game Board
valid_moves Valid Moves matrix to be filled with the given piece valid moves
lin Line of the Position to Check
col Column of the Position to Check
color Color of the piece
Definition at line 145 of file pieces.c.
References board, is_inside_board(), and isOwnPiecePos().
valid_knight_move()
void valid_knight_move (Board board[8][8], bool valid_moves[8][8], uint8_t lin, uint8_t col, uint8_t color)
Definition at line 205 of file pieces.c.
References board, is_inside_board(), and isOwnPiecePos().
valid_pawn_eat()
void valid_pawn_eat (Board board[8][8], bool valid_moves[8][8], uint8_t lin, uint8_t col, uint8_t color)
Checks if (lin,col) contains an enemy piece, saving value in valid_moves.
Parameters
board Current game Board
valid_moves Valid Moves matrix to be filled with the given piece valid moves
lin Line of the Position to Check
col Column of the Position to Check
color Color of the piece
Definition at line 64 of file pieces.c.
References board, and isEnemyPiecePos().
valid_pawn_move()
bool valid_pawn_move (Board board[8][8], bool valid_moves[8][8], uint8_t lin, uint8_t col, uint8_t color)
Checks available moves for a pawn in the given board in the given position and updates the valid_moves matrix with the computed results.
Parameters
board Current game Board
valid_moves Valid Moves matrix to be filled with the given piece valid moves
lin Current lin position of the piece
col Current col position of the piece
color Color of the piece
Returns
true if it is a empty space
false otherwise
Definition at line 58 of file pieces.c.
References Blank_space, board, and Piece::p_type.