Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/drivers/rtc/rtc.h File Reference
rtc.h File Reference
RTC API.
#include <lcom/lcf.h>
Macros
#define RTC_IRQ 8
#define RTC_ADDR_REG 0x70
#define RTC_DATA_REG 0x71
#define RTC_SEC 0
#define RTC_SEC_A 1
#define RTC_MIN 2
#define RTC_MIN_A 3
#define RTC_HOURS 4
#define RTC_HOURS_A 5
#define RTC_WEEK_DAY 6
#define RTC_DAY 7
#define RTC_MONTH 8
#define RTC_YEAR 9
#define RTC_REG_A 10
#define RTC_REG_B 11
#define RTC_REG_C 12
#define RTC_REG_D 13
#define RTC_UIP BIT(7)
#define RTC_SET BIT(7)
#define RTC_UIE BIT(4)
#define RTC_UF BIT(4)
#define RTC_AF BIT(5)
#define RTC_PF BIT(6)
Functions
int() enable_int_update (bool enable)
Enables/Disables Interrupt Updates for the RTC.
int() rtc_subscribe_int (uint8_t *bit_no)
Subscribes RTC Interrupts.
int() rtc_unsubscribe_int ()
Unsubscribes RTC Interrupts.
void() rtc_ih ()
Handles RTC Interrupts.
int() wait_rtc ()
Waits for the RTC to update its values.
uint8_t() bcd2dec (uint8_t bcdNum)
Converts Binary Coded Decimal to Decimal.
int() rtc_read (uint8_t reg, uint8_t pos)
Reads Value from Argument Field and Stores it in the global variable.
Detailed Description
RTC API.
Copyright
Copyright (c) 2022
Definition in file rtc.h.
Macro Definition Documentation
RTC_ADDR_REG
#define RTC_ADDR_REG 0x70
Definition at line 13 of file rtc.h.
RTC_AF
#define RTC_AF BIT(5)
Definition at line 41 of file rtc.h.
RTC_DATA_REG
#define RTC_DATA_REG 0x71
Definition at line 14 of file rtc.h.
RTC_DAY
#define RTC_DAY 7
Definition at line 24 of file rtc.h.
RTC_HOURS
#define RTC_HOURS 4
Definition at line 21 of file rtc.h.
RTC_HOURS_A
#define RTC_HOURS_A 5
Definition at line 22 of file rtc.h.
RTC_IRQ
#define RTC_IRQ 8
Definition at line 11 of file rtc.h.
RTC_MIN
#define RTC_MIN 2
Definition at line 19 of file rtc.h.
RTC_MIN_A
#define RTC_MIN_A 3
Definition at line 20 of file rtc.h.
RTC_MONTH
#define RTC_MONTH 8
Definition at line 25 of file rtc.h.
RTC_PF
#define RTC_PF BIT(6)
Definition at line 42 of file rtc.h.
RTC_REG_A
#define RTC_REG_A 10
Definition at line 29 of file rtc.h.
RTC_REG_B
#define RTC_REG_B 11
Definition at line 30 of file rtc.h.
RTC_REG_C
#define RTC_REG_C 12
Definition at line 31 of file rtc.h.
RTC_REG_D
#define RTC_REG_D 13
Definition at line 32 of file rtc.h.
RTC_SEC
#define RTC_SEC 0
Definition at line 17 of file rtc.h.
RTC_SEC_A
#define RTC_SEC_A 1
Definition at line 18 of file rtc.h.
RTC_SET
#define RTC_SET BIT(7)
Definition at line 36 of file rtc.h.
RTC_UF
#define RTC_UF BIT(4)
Definition at line 40 of file rtc.h.
RTC_UIE
#define RTC_UIE BIT(4)
Definition at line 37 of file rtc.h.
RTC_UIP
#define RTC_UIP BIT(7)
Definition at line 35 of file rtc.h.
RTC_WEEK_DAY
#define RTC_WEEK_DAY 6
Definition at line 23 of file rtc.h.
RTC_YEAR
#define RTC_YEAR 9
Definition at line 26 of file rtc.h.
Function Documentation
bcd2dec()
uint8_t() bcd2dec (uint8_t bcdNum)
Converts Binary Coded Decimal to Decimal.
Parameters
bcdNum Value expressed in Binary Coded Decimal
Returns
bcdNum value expressed in Decimal
Definition at line 74 of file rtc.c.
enable_int_update()
int() enable_int_update (bool enable)
Enables/Disables Interrupt Updates for the RTC.
Parameters
enable True for enabling, False for disabling
Returns
0 on success
Definition at line 7 of file rtc.c.
References RTC_ADDR_REG, RTC_DATA_REG, RTC_REG_B, and RTC_UIE.
rtc_ih()
void() rtc_ih ()
Handles RTC Interrupts.
Definition at line 37 of file rtc.c.
References RTC_ADDR_REG, RTC_DATA_REG, RTC_DAY, RTC_HOURS, RTC_MIN, RTC_MONTH, rtc_read(), RTC_REG_C, RTC_SEC, RTC_UF, and RTC_YEAR.
rtc_read()
int() rtc_read (uint8_t reg, uint8_t pos)
Reads Value from Argument Field and Stores it in the global variable.
Returns
0 on success
Definition at line 79 of file rtc.c.
References bcd2dec(), RTC_ADDR_REG, rtc_data, RTC_DATA_REG, and wait_rtc().
rtc_subscribe_int()
int() rtc_subscribe_int (uint8_t * bit_no)
Subscribes RTC Interrupts.
Parameters
bit_no Identifier of the interrupt to be subscribed
Returns
0 on success
Definition at line 24 of file rtc.c.
References enable_int_update(), rtc_hook_id, and RTC_IRQ.
rtc_unsubscribe_int()
int() rtc_unsubscribe_int ()
Unsubscribes RTC Interrupts.
Returns
0 on success
Definition at line 31 of file rtc.c.
References enable_int_update(), and rtc_hook_id.
wait_rtc()
int() wait_rtc ()
Waits for the RTC to update its values.
Returns
0 on success
Definition at line 56 of file rtc.c.
References RTC_ADDR_REG, RTC_DATA_REG, rtc_hook_id, RTC_REG_A, and RTC_UIP.