Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/drivers/rtc/rtc.c File Reference
rtc.c File Reference
#include "rtc.h"
Functions
int enable_int_update (bool enable)
Enables/Disables Interrupt Updates for the RTC.
int() rtc_subscribe_int (uint8_t *bit_no)
Subscribes RTC Interrupts.
int() rtc_unsubscribe_int ()
Unsubscribes RTC Interrupts.
void() rtc_ih ()
Handles RTC Interrupts.
int wait_rtc ()
Waits for the RTC to update its values.
uint8_t bcd2dec (uint8_t bcdNum)
Converts Binary Coded Decimal to Decimal.
int rtc_read (uint8_t val, uint8_t pos)
Reads Value from Argument Field and Stores it in the global variable.
Variables
uint8_t rtc_data [6]
static int rtc_hook_id
Function Documentation
bcd2dec()
uint8_t bcd2dec (uint8_t bcdNum)
Converts Binary Coded Decimal to Decimal.
Parameters
bcdNum Value expressed in Binary Coded Decimal
Returns
bcdNum value expressed in Decimal
Definition at line 74 of file rtc.c.
enable_int_update()
int enable_int_update (bool enable)
Enables/Disables Interrupt Updates for the RTC.
Parameters
enable True for enabling, False for disabling
Returns
0 on success
Definition at line 7 of file rtc.c.
References RTC_ADDR_REG, RTC_DATA_REG, RTC_REG_B, and RTC_UIE.
rtc_ih()
void() rtc_ih ()
Handles RTC Interrupts.
Definition at line 37 of file rtc.c.
References RTC_ADDR_REG, RTC_DATA_REG, RTC_DAY, RTC_HOURS, RTC_MIN, RTC_MONTH, rtc_read(), RTC_REG_C, RTC_SEC, RTC_UF, and RTC_YEAR.
rtc_read()
int rtc_read (uint8_t reg, uint8_t pos)
Reads Value from Argument Field and Stores it in the global variable.
Returns
0 on success
Definition at line 79 of file rtc.c.
References bcd2dec(), RTC_ADDR_REG, rtc_data, RTC_DATA_REG, and wait_rtc().
rtc_subscribe_int()
int() rtc_subscribe_int (uint8_t * bit_no)
Subscribes RTC Interrupts.
Parameters
bit_no Identifier of the interrupt to be subscribed
Returns
0 on success
Definition at line 24 of file rtc.c.
References enable_int_update(), rtc_hook_id, and RTC_IRQ.
rtc_unsubscribe_int()
int() rtc_unsubscribe_int ()
Unsubscribes RTC Interrupts.
Returns
0 on success
Definition at line 31 of file rtc.c.
References enable_int_update(), and rtc_hook_id.
wait_rtc()
int wait_rtc ()
Waits for the RTC to update its values.
Returns
0 on success
Definition at line 56 of file rtc.c.
References RTC_ADDR_REG, RTC_DATA_REG, rtc_hook_id, RTC_REG_A, and RTC_UIP.
Variable Documentation
rtc_data
uint8_t rtc_data[6]
Definition at line 3 of file rtc.c.
rtc_hook_id
int rtc_hook_id static
Definition at line 4 of file rtc.c.