Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/game/views/sprite/sprite.h File Reference
sprite.h File Reference
#include "lcom/lcf.h"
#include "../../../drivers/graphics/video_graphic.h"
Data Structures
struct sprite
Sprite struct defining an XPM loaded image.
Typedefs
typedef struct sprite sprite_t
Functions
sprite_t * make_sprite (const xpm_map_t xpm, enum xpm_image_type type)
Allocates a sprite_t object with the given xpm and the image type.
void free_sprite (sprite_t *p)
Frees a sprite_t struct memory.
unsigned int get_sprite_W (sprite_t *sprite)
Get the given sprite width.
unsigned int get_sprite_H (sprite_t *sprite)
Get the given sprite height.
unsigned int get_sprite_Y (sprite_t *sprite)
Get the given sprite y pos.
unsigned int get_sprite_X (sprite_t *sprite)
Get the given sprite x pos.
void set_sprite_Y (sprite_t *sprite, unsigned int y)
Set the sprite Y pos.
void set_sprite_X (sprite_t *sprite, unsigned int x)
Set the sprite X pos.
void set_sprite_pos (sprite_t *sprite, unsigned x, unsigned y)
Set the sprite (x,y) position.
uint8_t * get_sprite_map (sprite_t *sprite)
Gets the sprite's color map.
int draw_sprite_in_mode_14c (sprite_t *sprite)
Draws the given sprite in the 0x14C mode.
int draw_piece_in_mode_14c (uint8_t *map, int x, int y, unsigned int size)
Draws a chess piece in the given (x,y) pos using the provided color map.
int draw_text_sprite (sprite_t *sprite, int color_map)
Draw the given text sprite using the given color map.
int draw_sprite_in_mode_105 (sprite_t *sprite)
Draws the given sprite in the 0x105 mode.
Typedef Documentation
sprite_t
typedef struct sprite sprite_t
Definition at line 18 of file sprite.h.
Function Documentation
draw_piece_in_mode_14c()
int draw_piece_in_mode_14c (uint8_t * map, int x, int y, unsigned int size)
Draws a chess piece in the given (x,y) pos using the provided color map.
Parameters
map color map for the piece to be drawn
x x cord of where to draw the piece
y y cord of where to draw the piece
size number of width/height piece's pixels
Returns
int 0 if draw = Ok
draw_sprite_in_mode_105()
int draw_sprite_in_mode_105 (sprite_t * sprite)
Draws the given sprite in the 0x105 mode.
Parameters
sprite sprite to be drawn
Returns
int 0 if draw = Ok
Definition at line 116 of file sprite.c.
References fill_pixel(), get_sprite_map(), sprite::h, sprite::w, sprite::x, and sprite::y.
draw_sprite_in_mode_14c()
int draw_sprite_in_mode_14c (sprite_t * sprite)
Draws the given sprite in the 0x14C mode.
Parameters
sprite sprite to be drawn
Returns
int 0 if draw = Ok
Definition at line 53 of file sprite.c.
References fill_pixel(), get_hres(), get_sprite_map(), get_vres(), sprite::h, h_res, v_res, sprite::w, sprite::x, and sprite::y.
draw_text_sprite()
int draw_text_sprite (sprite_t * sprite, int color_map)
Draw the given text sprite using the given color map.
Parameters
sprite text sprite to be drawn
color_map color map to be used in the draw
Returns
int 0 if draw = Ok
Definition at line 76 of file sprite.c.
References fill_pixel(), get_hres(), get_sprite_map(), get_vres(), sprite::h, h_res, v_res, sprite::w, sprite::x, and sprite::y.
free_sprite()
void free_sprite (sprite_t * p)
Frees a sprite_t struct memory.
Parameters
p sprite to have its memory cleared
Definition at line 18 of file sprite.c.
References sprite::map.
get_sprite_H()
unsigned int get_sprite_H (sprite_t * sprite)
Get the given sprite height.
Parameters
sprite sprite to be used
Returns
unsigned int height of the given sprite
Definition at line 26 of file sprite.c.
References sprite::h.
get_sprite_map()
uint8_t * get_sprite_map (sprite_t * sprite)
Gets the sprite's color map.
Parameters
sprite sprite to be used
Returns
uint8_t* sprite's color map pointer
Definition at line 49 of file sprite.c.
References sprite::map.
get_sprite_W()
unsigned int get_sprite_W (sprite_t * sprite)
Get the given sprite width.
Parameters
sprite sprite to be used
Returns
unsigned int width of the given sprite
Definition at line 23 of file sprite.c.
References sprite::w.
get_sprite_X()
unsigned int get_sprite_X (sprite_t * sprite)
Get the given sprite x pos.
Parameters
sprite sprite to be used
Returns
unsigned int x pos of the given sprite
Definition at line 33 of file sprite.c.
References sprite::x.
get_sprite_Y()
unsigned int get_sprite_Y (sprite_t * sprite)
Get the given sprite y pos.
Parameters
sprite sprite to be used
Returns
unsigned int y pos of the given sprite
Definition at line 30 of file sprite.c.
References sprite::y.
make_sprite()
sprite_t * make_sprite (const xpm_map_t xpm, enum xpm_image_type type)
Allocates a sprite_t object with the given xpm and the image type.
Parameters
xpm xpm to be converted into a sprite
type image type to be considered
Returns
sprite_t* sprite_t object created
Definition at line 3 of file sprite.c.
References sprite::h, sprite::map, type, and sprite::w.
set_sprite_pos()
void set_sprite_pos (sprite_t * sprite, unsigned x, unsigned y)
Set the sprite (x,y) position.
Parameters
sprite sprite to be updated
x new sprite's x pos
y new sprite's y pos
Definition at line 44 of file sprite.c.
References sprite::x, and sprite::y.
set_sprite_X()
void set_sprite_X (sprite_t * sprite, unsigned int x)
Set the sprite X pos.
Parameters
sprite sprite to be updated
y new sprite's x pos
set_sprite_Y()
void set_sprite_Y (sprite_t * sprite, unsigned int y)
Set the sprite Y pos.
Parameters
sprite sprite to be updated
y new sprite's y pos