Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/drivers/timer/timer.c File Reference
timer.c File Reference
#include <lcom/lcf.h>
#include <lcom/timer.h>
#include <stdint.h>
#include "../utils/handlers.h"
#include "i8254.h"
Functions
int() timer_set_frequency (uint8_t timer, uint32_t freq)
int() timer_subscribe_int (uint8_t *bit_no)
int() timer_unsubscribe_int ()
void() timer_int_handler ()
int() timer_get_conf (uint8_t timer, uint8_t *st)
int() timer_display_conf (uint8_t timer, uint8_t st, enum timer_status_field field)
Variables
uint32_t n_interrupts = 0
int hook_id
Function Documentation
timer_display_conf()
int() timer_display_conf (uint8_t timer, uint8_t st, enum timer_status_field field)
Definition at line 70 of file timer.c.
References Assert_cbet, CHECKCall, CONF_BCD_MODE, CONF_COUNT_MODE, CONF_IN_MODE, FIRST_TIMER, and THIRD_TIMER.
timer_get_conf()
int() timer_get_conf (uint8_t timer, uint8_t * st)
<Read Back Command
<Control register
<Timer 0 count register
Definition at line 56 of file timer.c.
References Assert_cbet, CHECKCall, FIRST_TIMER, NullSafety, THIRD_TIMER, TIMER_0, TIMER_CTRL, TIMER_RB_CMD, TIMER_RB_COUNT_, TIMER_RB_SEL, and util_sys_inb().
timer_int_handler()
void() timer_int_handler ()
Definition at line 52 of file timer.c.
References n_interrupts.
timer_set_frequency()
int() timer_set_frequency (uint8_t timer, uint32_t freq)
<Hardware limitaion, it is 18.2hz
<clock frequency for timer in PC and AT
<Hardware limitaion, it is 18.2hz
<clock frequency for timer in PC and AT
<clock frequency for timer in PC and AT
<Control Word for Timer 0
<Initialize Counter LSB only
<Initialize Counter MSB only
<Initialize LSB first and MSB afterwards
less sig. half of a Unsigned byte bits (4 bits)
<Control register
<Timer 0 count register
Definition at line 12 of file timer.c.
References Assert_cbet, CHECKCall, LSHUB_IN_BYTE, TIMER_0, TIMER_BB_FREQ, TIMER_CTRL, TIMER_FREQ, timer_get_conf(), TIMER_LSB_MSB, TIMER_SEL, util_get_LSB(), and util_get_MSB().
timer_subscribe_int()
int() timer_subscribe_int (uint8_t * bit_no)
<Timer 0 IRQ line
Definition at line 37 of file timer.c.
References CHECKCall, hook_id, NullSafety, TIMER0_HOOK_ID, and TIMER0_IRQ.
timer_unsubscribe_int()
int() timer_unsubscribe_int ()
Definition at line 44 of file timer.c.
References CHECKCall, hook_id, and NullSafety.
Variable Documentation
hook_id
int hook_id
Definition at line 10 of file timer.c.
n_interrupts
uint32_t n_interrupts = 0
Definition at line 9 of file timer.c.