Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/drivers/serial_port/uart.c File Reference
uart.c File Reference
#include "uart.h"
#include "../utils/handlers.h"
#include "uart_defines.h"
Functions
int ser_set_bits_per_char (unsigned short base_addr, unsigned long bits)
Sets the nr of bits to send in a communication.
int ser_set_stop (unsigned short base_addr, unsigned long stop)
Sets the nr of stop bits.
int ser_set_par (unsigned short base_addr, long parity)
Sets the parity.
int enable_dlab (unsigned short base_addr)
Enables the Divisor Latch.
int disable_dlab (unsigned short base_addr)
Disables the Divisor Latch.
int ser_set_bitrate (unsigned short base_addr, unsigned long bitrate)
Sets the bit rate / baund rate.
int ser_test_set (unsigned short base_addr, unsigned long bits, unsigned long stop, long parity, unsigned long rate)
Sets the approriate configuration to use in the uart communication.
int set_ier (unsigned short base_addr, uint8_t ierToSet, bool enable)
Set the ier interrups desired, or disables them.
int ser_subscribe_int (uint8_t *bit_no, int *hook_id)
subscribes an serial interrupt
int ser_unsubscribe_int (int *hook_id)
unsubscribes an serial interrupt
int ser_writeb (unsigned short base_addr, uint8_t byte)
allows writing to the serial port transmitter
int ser_readb (unsigned short base_addr, uint8_t *byte)
reads a byte from the serial port received data
void uart_ih ()
Handles a uart ih.
int get_int_type ()
Get the type of interrupt that last occured on the serial port. This is used to try to make our serial ih more independent from the app, the fifo would be great for that.
Function Documentation
disable_dlab()
int disable_dlab (unsigned short base_addr)
Disables the Divisor Latch.
Parameters
base_addr base addr to use in comunnication
Returns
int
Definition at line 53 of file uart.c.
References CHECKCall, and UART_LCR.
enable_dlab()
int enable_dlab (unsigned short base_addr)
Enables the Divisor Latch.
Parameters
base_addr base addr to use in comunnication
Returns
int
Definition at line 44 of file uart.c.
References CHECKCall, LCR_DLAB, and UART_LCR.
get_int_type()
int get_int_type ()
Get the type of interrupt that last occured on the serial port. This is used to try to make our serial ih more independent from the app, the fifo would be great for that.
Returns
int
Definition at line 150 of file uart.c.
References type.
ser_readb()
int ser_readb (unsigned short base_addr, uint8_t * byte)
reads a byte from the serial port received data
Parameters
base_addr base addr to use in comunnication
byte the place to store the read
Returns
int
Definition at line 126 of file uart.c.
References CHECKCall, UART_RBR, and util_sys_inb().
ser_set_bitrate()
int ser_set_bitrate (unsigned short base_addr, unsigned long bitrate)
Sets the bit rate / baund rate.
Parameters
base_addr base addr to use in comunnication
bitrate the desired bit rate
Returns
int
Definition at line 62 of file uart.c.
References CHECKCall, COM1_ADDR, disable_dlab(), enable_dlab(), UART_BITRATE, UART_DLL, UART_DLM, util_get_LSB(), and util_get_MSB().
ser_set_bits_per_char()
int ser_set_bits_per_char (unsigned short base_addr, unsigned long bits)
Sets the nr of bits to send in a communication.
Parameters
base_addr base addr to use in comunnication
bits the desired number
Returns
int
Definition at line 5 of file uart.c.
References CHECKCall, and UART_LCR.
ser_set_par()
int ser_set_par (unsigned short base_addr, long parity)
Sets the parity.
Parameters
base_addr base addr to use in comunnication
parity the desired parity
Returns
int
Definition at line 33 of file uart.c.
References CHECKCall, and UART_LCR.
ser_set_stop()
int ser_set_stop (unsigned short base_addr, unsigned long stop)
Sets the nr of stop bits.
Parameters
base_addr base addr to use in comunnication
stop stops bits
Returns
int
Definition at line 17 of file uart.c.
References CHECKCall, and UART_LCR.
ser_subscribe_int()
int ser_subscribe_int (uint8_t * bit_no, int * hook_id)
subscribes an serial interrupt
Parameters
bit_no the bit num attached to the interrupt
hook_id hook id that identifies the interrupt
Returns
int
Definition at line 107 of file uart.c.
References CHECKCall, COM1_IRQ, and hook_id.
ser_test_set()
int ser_test_set (unsigned short base_addr, unsigned long bits, unsigned long stop, long parity, unsigned long rate)
Sets the approriate configuration to use in the uart communication.
Parameters
base_addr base addr to use in comunnication
bits bits per char
stop nr.stop bits
parity parity ... -1: none, 0: even, 1: odd
rate baund rate
Returns
int
Definition at line 78 of file uart.c.
References CHECKCall, ser_set_bitrate(), ser_set_bits_per_char(), ser_set_par(), and ser_set_stop().
ser_unsubscribe_int()
int ser_unsubscribe_int (int * hook_id)
unsubscribes an serial interrupt
Parameters
hook_id the identifier of the interrupt
Returns
int
Definition at line 116 of file uart.c.
References CHECKCall, and hook_id.
ser_writeb()
int ser_writeb (unsigned short base_addr, uint8_t byte)
allows writing to the serial port transmitter
Parameters
base_addr base addr to use in comunnication
byte the byte to send to the uart
Returns
int
Definition at line 121 of file uart.c.
References CHECKCall, and UART_THR.
set_ier()
int set_ier (unsigned short base_addr, uint8_t ierToSet, bool enable)
Set the ier interrups desired, or disables them.
Parameters
base_addr base addr to use in comunnication
ierToSet a byte with the wanted interrups set
enable name is explanatory, true to enable, else disable
Returns
int
Definition at line 92 of file uart.c.
References CHECKCall, UART_IER, and util_sys_inb().
uart_ih()
void uart_ih ()
Handles a uart ih.
Definition at line 131 of file uart.c.
References CHECKCall, COM1_ADDR, ERROR, IER_RECEIVED_INT, RECEIVE_DATA, SER_INT_ID, SER_RLS_INT, SER_RX_INT, SER_TX_INT, TX_EMPTY, type, UART_IIR, and util_sys_inb().