Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/drivers/graphics/video_graphic.c File Reference
video_graphic.c File Reference
#include "video_graphic.h"
Functions
int() vbe_set_mode (uint16_t mode)
Gets VBE Mode info for the specified mode and sets it with a BIOS Call.
int() map_vram (uint16_t mode)
Maps Video Memory to VRAM according to mode info.
int() fill_pixel (uint16_t x, uint16_t y, uint32_t color)
Changes Color of a pixel.
int() flush_screen ()
Copies auxiliar buffer memory into the physicall memory buffer.
int() vg_draw_hline (uint16_t x, uint16_t y, uint16_t len, uint32_t color)
Uses (fill_pixel) to draw an horizontal line.
int() vg_draw_rectangle (uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint32_t color)
Draws a Rectangle using (vg_draw_hline)
void *() video_graphic_init (uint16_t mode)
Maps Video Memory to VRAM calling (map_vram) and then sets VBE mode with (vbe_set_mode)
bool() is_indexed_mode (uint16_t mode)
Returns boolean if given mode is indexed.
unsigned() get_hres (void)
Returns Horizontal Resolution in Pixels of Current Mode.
unsigned() get_vres (void)
Returns Vertical Resolution in Pixels of Current Mode.
unsigned() get_bits_per_pixel (void)
Returns Amount of Bits that Represent a Pixel in Current Mode.
uint8_t() getRedMaskSize (void)
Returns Red Mask Size.
uint8_t() getGreenMaskSize (void)
Returns Green Mask Size.
uint8_t() getBlueMaskSize (void)
Returns Blue Mask Size.
uint8_t() getRedFieldPosition (void)
Returns Red Field Position.
uint8_t() getGreenFieldPosition (void)
Returns Green Field Position.
uint8_t() getBlueFieldPosition (void)
Returns Blue Field Position.
Function Documentation
fill_pixel()
int() fill_pixel (uint16_t x, uint16_t y, uint32_t color)
Changes Color of a pixel.
Parameters
x X coordinate of pixel
y Y coordinate of pixel
color Color code for the desired color for the pixel
Definition at line 72 of file video_graphic.c.
References buf, and h_res.
flush_screen()
int() flush_screen ()
Copies auxiliar buffer memory into the physicall memory buffer.
Returns
EXIT_SUCCESS if it finishes successfully
Definition at line 85 of file video_graphic.c.
References buf, video_mem, and vram_size.
get_bits_per_pixel()
unsigned() get_bits_per_pixel (void)
Returns Amount of Bits that Represent a Pixel in Current Mode.
Returns
Bits per pixel in Current Mode
Definition at line 126 of file video_graphic.c.
References bits_per_pixel.
get_hres()
unsigned() get_hres (void)
Returns Horizontal Resolution in Pixels of Current Mode.
Returns
Value of the horizontal resolution of the current graphics mode
Definition at line 118 of file video_graphic.c.
References h_res.
get_vres()
unsigned() get_vres (void)
Returns Vertical Resolution in Pixels of Current Mode.
Returns
Value of the Vertical resolution of the current graphics mode
Definition at line 122 of file video_graphic.c.
References v_res.
getBlueFieldPosition()
uint8_t() getBlueFieldPosition (void)
Returns Blue Field Position.
Returns
Blue Field Position
Definition at line 146 of file video_graphic.c.
References BlueFieldPosition.
getBlueMaskSize()
uint8_t() getBlueMaskSize (void)
Returns Blue Mask Size.
Returns
Blue Mask Size
Definition at line 136 of file video_graphic.c.
References BlueMaskSize.
getGreenFieldPosition()
uint8_t() getGreenFieldPosition (void)
Returns Green Field Position.
Returns
Green Field Position
Definition at line 143 of file video_graphic.c.
References GreenFieldPosition.
getGreenMaskSize()
uint8_t() getGreenMaskSize (void)
Returns Green Mask Size.
Returns
Green Mask Size
Definition at line 133 of file video_graphic.c.
References GreenMaskSize.
getRedFieldPosition()
uint8_t() getRedFieldPosition (void)
Returns Red Field Position.
Returns
Red Field Position
Definition at line 140 of file video_graphic.c.
References RedFieldPosition.
getRedMaskSize()
uint8_t() getRedMaskSize (void)
Returns Red Mask Size.
Returns
Red Mask Size
Definition at line 130 of file video_graphic.c.
References RedMaskSize.
is_indexed_mode()
bool() is_indexed_mode (uint16_t mode)
Returns boolean if given mode is indexed.
Returns
boolean if given mode is indexed
Definition at line 114 of file video_graphic.c.
References INDEXED_1024_768.
map_vram()
int() map_vram (uint16_t mode)
Maps Video Memory to VRAM according to mode info.
Parameters
mode Graphics Mode to be used
Returns
EXIT_SUCCESS if it finishes successfully
Definition at line 25 of file video_graphic.c.
References bits_per_pixel, BlueFieldPosition, BlueMaskSize, buf, CHECKCall, color_model, GreenFieldPosition, GreenMaskSize, h_res, r, RedFieldPosition, RedMaskSize, v_res, video_mem, and vram_size.
vbe_set_mode()
int() vbe_set_mode (uint16_t mode)
Gets VBE Mode info for the specified mode and sets it with a BIOS Call.
Parameters
mode Mode for the VBE to be set
Returns
EXIT_SUCCESS if it finishes successfully
Definition at line 3 of file video_graphic.c.
References CHECKCall, LINEAR_BUF, VBE_CALL, VBE_SET_MODE, and VC_BIOS_SERV.
vg_draw_hline()
int() vg_draw_hline (uint16_t x, uint16_t y, uint16_t len, uint32_t color)
Uses (fill_pixel) to draw an horizontal line.
Parameters
x Leftmost Pixel's X Coordinate
y Leftmost Pixel´s Y Coordinate
len Line's Length in pixels
color Color code for the desired color for the line
Returns
EXIT_SUCCESS if it finishes successfully
Definition at line 91 of file video_graphic.c.
References CHECKCall, and fill_pixel().
vg_draw_rectangle()
int() vg_draw_rectangle (uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint32_t color)
Draws a Rectangle using (vg_draw_hline)
Parameters
x X Coordinate of the pixel in the upper left corner of the rectangle
y Y Coordinate of the pixel in the upper left corner of the rectangle
width Rectangle's width in pixels
height Rectangle's height in pixels
color Rectangle's color code
Returns
EXIT_SUCCESS if it finishes successfully
Definition at line 99 of file video_graphic.c.
References CHECKCall, and vg_draw_hline().
video_graphic_init()
void *() video_graphic_init (uint16_t mode)
Maps Video Memory to VRAM calling (map_vram) and then sets VBE mode with (vbe_set_mode)
Parameters
mode Mode to initialize the video graphic to
Definition at line 106 of file video_graphic.c.
References buf, CHECKCall, map_vram(), and vbe_set_mode().