Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/game/game.h File Reference
game.h File Reference
#include <lcom/lcf.h>
#include "../drivers/graphics/video_graphic.h"
#include "../drivers/kbc/i8042.h"
#include "../drivers/keyboard/kbd_keys.h"
#include "../drivers/keyboard/keyboard.h"
#include "../drivers/mouse/mouse.h"
#include "int_handlers/dependent/dependent_ih.h"
#include "int_handlers/independent/independent_ih.h"
#include "views/font/font.h"
#include "views/sprite/sprite.h"
Functions
void game_loop ()
Allocs game sprites, subscrives interrupts and manages event handlers. Also unsubscribes the IHs and frees the sprites allocation at the end of the program.
Function Documentation
game_loop()
void game_loop ()
Allocs game sprites, subscrives interrupts and manages event handlers. Also unsubscribes the IHs and frees the sprites allocation at the end of the program.
Definition at line 4 of file game.c.
References BREAK_EVT, flush_screen(), free_view(), handle_evt(), handle_ihs(), set_up_board(), set_up_view(), subscribe_ihs(), unsubscribe_ihs(), and user_msg.