Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/drivers/kbc/kbc.h File Reference
kbc.h File Reference
Kbc Api used by mouse and kbd.
#include <lcom/lcf.h>
#include "../utils/handlers.h"
#include "i8042.h"
Functions
int() subscribe_kbc_interrupt (uint8_t bit_no, int *hook_id, int kbc)
Subscribes interrupts from the keyboard controller.
int() unsubscribe_interrupt (int *hook_id)
Unsubscribes interrupts from the keyboard controller.
int() kbc_read_i ()
Tries to read keyboard scancodes and mouse packets.
bool() kbc_get_error ()
Returns the error flag that was set when the error occurred.
void() kbc_ih (void)
Handles KBC Interrupts.
bool() kbc_ready ()
Checks if the last read byte was the last byte of a scancode or not.
bool() kbc_mouse_ready ()
Checks if the currently received packet is already completed.
void() kbc_get_scancode (unsigned char *scan, int *scan_sz)
Get the last scancode read in a given array.
void() kbc_get_mouse_data (unsigned char *scan)
Get the last mouse packet read in a given array.
int() kbc_read (uint8_t *code)
Reads content of the Output Buffer if it is full.
int() kbc_issue_cmd (uint8_t cmd)
Reads status register and then writes command on the KBC Command Register.
int() kbc_read_cmd (uint8_t *cmd)
Issues a Reading Command and Reads the Command from the Output Buffer.
int() kbc_write_cmd (uint8_t cmd)
Issues a Writing Command and then Writes the Command to the Output Buffer.
int() kbc_send_mouse_cmd (uint8_t cmd)
Send given command to the mouse.
int() kbc_cmd_arg (uint8_t arg)
Send arg to the kbd.
int() kbc_check_cmd ()
Issues a Check Command and Reads the KBC State. Prints an error message in case of errors.
Variables
uint8_t scancode [2]
uint8_t mouse_data [3]
uint8_t mouse_received_count
bool mouse_packet_completed
int scancode_sz
bool two_byte_scancode
bool error_flag
Detailed Description
Kbc Api used by mouse and kbd.
Copyright
Copyright (c) 2022
Definition in file kbc.h.
Function Documentation
kbc_check_cmd()
int() kbc_check_cmd ()
Issues a Check Command and Reads the KBC State. Prints an error message in case of errors.
Returns
EXIT_SUCCESS if KBC is ok, 1 Otherwise
Definition at line 145 of file kbc.c.
References CHECKCall, KBC_CHECK, KBC_CHECK_ERROR, kbc_issue_cmd(), kbc_read(), and state.
kbc_cmd_arg()
int() kbc_cmd_arg (uint8_t arg)
Send arg to the kbd.
Parameters
cmd arg to be sent
Definition at line 162 of file kbc.c.
References CHECKCall, DELAY_US, IN_BUF_FULL, KBC_CMD_ARG, KBC_ST_REG, and util_sys_inb().
kbc_get_error()
bool() kbc_get_error ()
Returns the error flag that was set when the error occurred.
Returns
Flag identifying the error that occurred
Definition at line 91 of file kbc.c.
References error_flag.
kbc_get_mouse_data()
void() kbc_get_mouse_data (unsigned char * scan)
Get the last mouse packet read in a given array.
Parameters
*scan Array to be filled with the packet
Definition at line 86 of file kbc.c.
References mouse_data, and scan.
kbc_get_scancode()
void() kbc_get_scancode (unsigned char * scan, int * scan_sz)
Get the last scancode read in a given array.
Parameters
*scan Pointer to the array to receive the scancode
*scan_sz Pointer to the Size of the Scancode array
Definition at line 80 of file kbc.c.
References scan, scancode, and scancode_sz.
kbc_ih()
void() kbc_ih (void)
Handles KBC Interrupts.
Definition at line 68 of file kbc.c.
References error_flag, and kbc_read_i().
kbc_issue_cmd()
int() kbc_issue_cmd (uint8_t cmd)
Reads status register and then writes command on the KBC Command Register.
Parameters
cmd Command to be issued
Returns
EXIT_SUCCESS on success
Definition at line 117 of file kbc.c.
References CHECKCall, DELAY_US, IN_BUF_FULL, KBC_CMD_REG, KBC_ST_REG, and util_sys_inb().
kbc_mouse_ready()
bool() kbc_mouse_ready ()
Checks if the currently received packet is already completed.
Returns
True if it is or False if it isn't
Definition at line 158 of file kbc.c.
References mouse_packet_completed.
kbc_read()
int() kbc_read (uint8_t * code)
Reads content of the Output Buffer if it is full.
Parameters
*scan pointer to where the values read should be stored.
Returns
EXIT_SUCCESS in case it suceeds, EXIT_FAILURE in case there is a parity/timeout error or buffer is not full
Definition at line 95 of file kbc.c.
References CHECKCall, DELAY_US, KBC_ST_REG, OUT_BUF, OUT_BUF_FULL, PARITY_ERROR, TIMEOUT_ERROR, and util_sys_inb().
kbc_read_cmd()
int() kbc_read_cmd (uint8_t * cmd)
Issues a Reading Command and Reads the Command from the Output Buffer.
Parameters
cmd Variable where the read command is going to be stored
Returns
EXIT_SUCCESS on success
Definition at line 133 of file kbc.c.
References CHECKCall, kbc_issue_cmd(), kbc_read(), and KBC_READ_CMD.
kbc_read_i()
int() kbc_read_i ()
Tries to read keyboard scancodes and mouse packets.
Returns
EXIT_SUCCESS on success or EXIT_FAILURE if an error occurs
Definition at line 26 of file kbc.c.
References AUX_MOUSE, CHECKCall, KBC_ST_REG, mouse_data, mouse_packet_completed, mouse_received_count, OUT_BUF, OUT_BUF_FULL, PARITY_ERROR, scancode, scancode_sz, TIMEOUT_ERROR, TWO_BYTE_CODE, two_byte_scancode, and util_sys_inb().
kbc_ready()
bool() kbc_ready ()
Checks if the last read byte was the last byte of a scancode or not.
Returns
True if the read byte isn't 0xE0 (first byte of the two byte scancode) or False if it is
Definition at line 76 of file kbc.c.
References two_byte_scancode.
kbc_send_mouse_cmd()
int() kbc_send_mouse_cmd (uint8_t cmd)
Send given command to the mouse.
Parameters
cmd command to be sent
Definition at line 177 of file kbc.c.
References ACK, CHECKCall, KBC_CHECK_ERROR, kbc_cmd_arg(), kbc_issue_cmd(), NACK, OUT_BUF, util_sys_inb(), and WRITE_BYTE_MOUSE.
kbc_write_cmd()
int() kbc_write_cmd (uint8_t cmd)
Issues a Writing Command and then Writes the Command to the Output Buffer.
Parameters
cmd Command to be written
Returns
EXIT_SUCCESS on success
Definition at line 139 of file kbc.c.
References CHECKCall, kbc_issue_cmd(), KBC_WRITE_CMD, and OUT_BUF.
subscribe_kbc_interrupt()
int() subscribe_kbc_interrupt (uint8_t bit_no, int * hook_id, int kbc)
Subscribes interrupts from the keyboard controller.
Parameters
bit_no Address of memory to be initialized with the bit number to be set in the mask returned upon an interrupt
*hook_id Identifier of the interrupt to be subscribed
kbc IRQ Line for the Keyboard Controller
Returns
EXIT_SUCCESS on success or EXIT_FAILURE if an error occurs
Definition at line 12 of file kbc.c.
References CHECKCall, hook_id, and NullSafety.
unsubscribe_interrupt()
int() unsubscribe_interrupt (int * hook_id)
Unsubscribes interrupts from the keyboard controller.
Parameters
*hook_id Identifier of the interrupt to be unsubscribed
Returns
EXIT_SUCCESS on success or EXIT_FAILURE if an error occurs
Definition at line 20 of file kbc.c.
References CHECKCall, hook_id, and NullSafety.
Variable Documentation
error_flag
bool error_flag
Definition at line 22 of file kbc.h.
mouse_data
uint8_t mouse_data[3]
Definition at line 17 of file kbc.h.
mouse_packet_completed
bool mouse_packet_completed
Definition at line 19 of file kbc.h.
mouse_received_count
uint8_t mouse_received_count
Definition at line 18 of file kbc.h.
scancode
uint8_t scancode[2]
Definition at line 16 of file kbc.h.
scancode_sz
int scancode_sz
Definition at line 20 of file kbc.h.
two_byte_scancode
bool two_byte_scancode
Definition at line 21 of file kbc.h.