Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/game/state_machine/mouse_st.c File Reference
mouse_st.c File Reference
#include "mouse_st.h"
Functions
int entry_state (struct mouse_ev *event)
Sets the mouse entry state based on the given event.
int grab_state (struct mouse_ev *event)
Sets the mouse grab state based on the given event.
int pick_state (struct mouse_ev *event)
Sets the mouse pick state based on the given event.
int exit_state (struct mouse_ev *event)
Sets the mouse exit state based on the given event.
enum state_codes lookup_transitions (int cur_state, int rc)
Updates the mouse machine state based on the given state and the given kbd state.
void set_can_move (bool move)
Sets if the move can be done in online game, being an empty transmitter indicator.
bool get_can_move ()
Get the can move boolean, indicating is move can be done.
Variables
int(* state [])(struct mouse_ev *event) = {entry_state, grab_state, pick_state, exit_state}
Function Documentation
entry_state()
int entry_state (struct mouse_ev * event)
Sets the mouse entry state based on the given event.
Parameters
event mouse event to be evaluated
Returns
ret code of state
Definition at line 5 of file mouse_st.c.
References get_cursor_X(), get_cursor_Y(), ok, repeat, and set_selected_case().
exit_state()
int exit_state (struct mouse_ev * event)
Sets the mouse exit state based on the given event.
Parameters
event mouse event to be evaluated
Returns
ret code of state
Definition at line 127 of file mouse_st.c.
References ok.
get_can_move()
bool get_can_move ()
Get the can move boolean, indicating is move can be done.
Returns
true can move
false cannot move
Definition at line 164 of file mouse_st.c.
References can_move.
grab_state()
int grab_state (struct mouse_ev * event)
Sets the mouse grab state based on the given event.
Parameters
event mouse event to be evaluated
Returns
ret code of state
Definition at line 13 of file mouse_st.c.
References back, BLACK, can_move, CHECKCall, COM1_ADDR, encode_protocol(), fail, get_cursor_X(), get_cursor_Y(), get_menu_state(), get_mouse_case(), get_online_color(), get_piece_at_pos_color(), get_selected_col(), get_selected_lin(), is_selected_case(), is_valid_move(), move_piece(), ok, online, Protocol::origin, repeat, ser_writeb(), and WHITE.
lookup_transitions()
enum state_codes lookup_transitions (int cur_state, int rc)
Updates the mouse machine state based on the given state and the given kbd state.
Parameters
cur_state current mouse state
rc kbd current state
Returns
enum state_codes new mouse state
Definition at line 131 of file mouse_st.c.
References back, cur_state, transition::dst_state, end, entry, fail, grab, ok, pick, rc, and repeat.
pick_state()
int pick_state (struct mouse_ev * event)
Sets the mouse pick state based on the given event.
Parameters
event mouse event to be evaluated
Returns
ret code of state
Definition at line 73 of file mouse_st.c.
References BLACK, can_move, CHECKCall, COM1_ADDR, encode_protocol(), fail, get_cursor_X(), get_cursor_Y(), get_menu_state(), get_mouse_case(), get_online_color(), get_piece_at_pos_color(), get_selected_col(), get_selected_lin(), is_valid_move(), move_piece(), ok, online, Protocol::origin, repeat, ser_writeb(), and WHITE.
set_can_move()
void set_can_move (bool move)
Sets if the move can be done in online game, being an empty transmitter indicator.
Parameters
move boolean if move can be done
Definition at line 160 of file mouse_st.c.
References can_move.
Variable Documentation
state
int(* state[])(struct mouse_ev *event) (struct mouse_ev * event) = {entry_state, grab_state, pick_state, exit_state}
Definition at line 3 of file mouse_st.c.