Lcom-Animated-Chess: C:/Users/ricar/OneDrive/Ambiente de Trabalho/MINIX/MINIX-LCOM/shared/proj/src/game/views/views.h File Reference
views.h File Reference
#include <lcom/lcf.h>
#include "../../drivers/graphics/video_graphic.h"
#include "../../drivers/mouse/mouse.h"
#include "../objects/pieces.h"
#include "../state_machine/menu_st.h"
#include "font/font.h"
#include "sprite/sprite.h"
#include "../../assets/menus/base_bg.xpm"
#include "../../assets/menus/instructions_menu.xpm"
#include "../../assets/menus/play_menu.xpm"
#include "../../assets/menus/start_menu.xpm"
#include "../../assets/select.xpm"
#include "../../assets/menus/buttons/button_back_S.xpm"
#include "../../assets/menus/buttons/button_exit_NS.xpm"
#include "../../assets/menus/buttons/button_exit_S.xpm"
#include "../../assets/menus/buttons/button_instructions_S.xpm"
#include "../../assets/menus/buttons/button_multiplayer_S.xpm"
#include "../../assets/menus/buttons/button_online_S.xpm"
#include "../../assets/menus/buttons/button_play_S.xpm"
#include "../../assets/animation/explosion.xpm"
#include "animation/animation.h"
#include "../../assets/animation/pieces/bB.xpm"
#include "../../assets/animation/pieces/bK.xpm"
#include "../../assets/animation/pieces/bN.xpm"
#include "../../assets/animation/pieces/bP.xpm"
#include "../../assets/animation/pieces/bQ.xpm"
#include "../../assets/animation/pieces/bR.xpm"
#include "../../assets/animation/pieces/wB.xpm"
#include "../../assets/animation/pieces/wK.xpm"
#include "../../assets/animation/pieces/wN.xpm"
#include "../../assets/animation/pieces/wP.xpm"
#include "../../assets/animation/pieces/wQ.xpm"
#include "../../assets/animation/pieces/wR.xpm"
Macros
#define BOARD_START_POS_X 0
#define BOARD_START_POS_Y 0
#define BOARD_SCREEN_CASE_SIZE 94
#define BOARD_SCREEN_SIZE 800
#define BOARD_NUMBER_OF_CASES 64
#define BOARD_NUMBER_OF_COL 8
#define BOARD_NUMBER_OF_LIN 8
#define BOARD_BLACK_CASE_COLOR 0x769656
#define BOARD_WHITE_CASE_COLOR 0xeeeed2
#define GAME_MODE 1
#define GAME_DURATION 300
Functions
void set_connected (bool isconnected)
Set the connected boolean in online gaming.
void draw_board ()
Draws the chess board.
void draw_pieces (Board table[8][8])
Draws the pieces on the given board.
void draw_piece (Board piece, unsigned int x, unsigned int y)
Draws a specific piece object in the specified coordinates.
void draw_clock ()
Draws RTC Clock in the Main menu.
void get_selected_valid_moves (bool arr[8][8])
Get the selected valid moves and returns them in the given matrix.
bool is_valid_move (int lin, int col)
Checks if moving to (lin,col) is valid.
void set_selected_case (int lin, int col)
Set the selected case object as (lin,col)
bool is_selected_case (int lin, int col)
Check if (lin,col) is the selected case.
void get_mouse_case (int m_y, int m_x, uint8_t *col, uint8_t *lin)
Gets the mouse current hovering piece/ board square.
void move_piece (int lin, int col)
Move selected piece to given cords.
void move_piece_from_to (uint8_t i_line, uint8_t i_col, uint8_t f_line, uint8_t final_col)
Moves piece from (i_line,i_col) to (f_line,f_col)
void set_up_view ()
Memory allocation for essential game sprites and positions.
void free_view ()
Frees all allocated memory of the game sprites.
void set_kbd_selected_opt (bool up)
Move up kbd menu pointed option.
int get_kbd_selected_opt ()
Get the kbd selected menu option.
int get_cursor_X ()
Get the cursor X pos.
int get_cursor_Y ()
Get the cursor Y pos.
uint8_t get_selected_col ()
Get the selected col in the chess board.
uint8_t get_selected_lin ()
Get the selected lin in the chess board.
void draw_game (bool startClock)
Draws all game components. That includes the board, pieces timers, available positions and respective animations.
void draw_update ()
Updates the frame by drawing a new menu frame and the new mouse cursor position.
void game_set_state (enum menu_state_codes state)
Updates the game state to the given state.
void mouse_update_pos (int x, int y)
Update mouse cords to the given x,y position.
void set_up_board ()
Allocates all pieces animation sprites and sets their position on the chess board.
void free_board ()
Frees all memory allocated for the animated pieces.
void draw_game_clock (bool game_started)
Draws both W and B game clocks current time.
void update_timer (bool white)
Updates the game timer based on RTC second changes.
void set_online_color (bool isWhite)
Set the online color for the current player's turn.
bool get_online_color ()
Get the online color for the current player's turn.
Piece_Color get_piece_at_pos_color (uint8_t lin, uint8_t col)
Get the piece's color at the given positon on the game board.
void buttonHoverDraw (sprite_t *sprite, unsigned x, unsigned y, int rc)
Draws the given sprite in the given position if the mouse is hover its drawn position or the kbd selected that button position in the game menus.
Variables
sprite_t * explosion_sp
AnimSprite * explosion
static sprite_t * bg_base
static sprite_t * bg_start
static sprite_t * bg_play
static sprite_t * bg_instructions
static sprite_t * buton_back_S
static sprite_t * buton_exit_NS
static sprite_t * buton_exit_S
static sprite_t * buton_instructions_S
static sprite_t * buton_multiplayer_S
static sprite_t * buton_online_S
static sprite_t * buton_play_S
static sprite_t * play_square_select
static sprite_t * game_exit_sprite
static mouse_ptr cursor
static bool moves [8][8]
static bool isWhitesTurn = true
static bool isWhiteInOnline = true
static bool hasconnected = false
static uint8_t select_lin = 0
static uint8_t select_col = 0
static int gameStateFlag = 0
static int white_clock = 300 + 1
static int black_clock = 300
static int startTime
static Board board [8][8]
static Board empty_case
static enum menu_state_codes game_cur_state = menu_entry
static int kbd_selected_opt = 0
Macro Definition Documentation
BOARD_BLACK_CASE_COLOR
#define BOARD_BLACK_CASE_COLOR 0x769656
Definition at line 65 of file views.h.
BOARD_NUMBER_OF_CASES
#define BOARD_NUMBER_OF_CASES 64
Definition at line 61 of file views.h.
BOARD_NUMBER_OF_COL
#define BOARD_NUMBER_OF_COL 8
Definition at line 62 of file views.h.
BOARD_NUMBER_OF_LIN
#define BOARD_NUMBER_OF_LIN 8
Definition at line 63 of file views.h.
BOARD_SCREEN_CASE_SIZE
#define BOARD_SCREEN_CASE_SIZE 94
Definition at line 58 of file views.h.
BOARD_SCREEN_SIZE
#define BOARD_SCREEN_SIZE 800
Definition at line 59 of file views.h.
BOARD_START_POS_X
#define BOARD_START_POS_X 0
Definition at line 55 of file views.h.
BOARD_START_POS_Y
#define BOARD_START_POS_Y 0
Definition at line 56 of file views.h.
BOARD_WHITE_CASE_COLOR
#define BOARD_WHITE_CASE_COLOR 0xeeeed2
Definition at line 66 of file views.h.
GAME_DURATION
#define GAME_DURATION 300
Definition at line 116 of file views.h.
GAME_MODE
#define GAME_MODE 1
Definition at line 68 of file views.h.
Function Documentation
buttonHoverDraw()
void buttonHoverDraw (sprite_t * sprite, unsigned x, unsigned y, int rc)
Draws the given sprite in the given position if the mouse is hover its drawn position or the kbd selected that button position in the game menus.
Parameters
sprite button sprite to be drawn
x where to draw X
y where to draw Y
rc kbd currently selected button in the menu
Definition at line 179 of file views.c.
References cursor, draw_sprite(), kbd_selected_opt, rc, sprite::x, and sprite::y.
draw_board()
void draw_board ()
Draws the chess board.
Definition at line 15 of file views.c.
References BOARD_BLACK_CASE_COLOR, BOARD_SCREEN_CASE_SIZE, BOARD_SIZE, BOARD_WHITE_CASE_COLOR, get_square_color(), lookUpTable, vg_draw_rectangle(), and WHITE.
draw_clock()
void draw_clock ()
Draws RTC Clock in the Main menu.
Definition at line 60 of file views.c.
References draw_text(), and rtc_data.
draw_game()
void draw_game (bool startClock)
Draws all game components. That includes the board, pieces timers, available positions and respective animations.
Parameters
startClock boolean if chess game clocks should be ticking
Definition at line 229 of file views.c.
References animation_counter, bg_base, board, buton_exit_NS, buton_exit_S, buttonHoverDraw(), count_exploding, draw_animSprite(), draw_bg(), draw_board(), draw_game_clock(), draw_pieces(), draw_sprite(), draw_text(), exploding_x, exploding_y, explosion, gameStateFlag, isWhitesTurn, menu_back, n_interrupts, AnimSprite::num_fig, and vg_draw_rectangle().
draw_game_clock()
void draw_game_clock (bool game_started)
Draws both W and B game clocks current time.
Parameters
game_started boolean if the times should be updated
Definition at line 564 of file views.c.
References black_clock, draw_text(), isWhitesTurn, updateTimer(), and white_clock.
draw_piece()
void draw_piece (Board piece, unsigned int x, unsigned int y)
Draws a specific piece object in the specified coordinates.
Parameters
piece chess piece to be drawn
x X Coordinate where the piece should be drawn
y Y Coordinate where the piece should be drawn
Definition at line 37 of file views.c.
References animation_counter, Piece::animSprite, BLACK, board, Piece::color, create_animSprite(), draw_animSprite(), lookUpTable, make_piece(), make_sprite(), AnimSprite::num_fig, Piece::p_type, Pawn, Queen, and WHITE.
draw_pieces()
void draw_pieces (Board table[8][8])
Draws the pieces on the given board.
Parameters
table 8x8 Board received for chess game
Definition at line 22 of file views.c.
References Blank_space, BOARD_SIZE, draw_piece(), draw_sprite_in_mode_14c(), get_valid_moves(), isWhitesTurn, lookUpTable, moves, play_square_select, select_col, select_lin, and set_sprite_pos().
draw_update()
void draw_update ()
Updates the frame by drawing a new menu frame and the new mouse cursor position.
Definition at line 275 of file views.c.
References draw_cursor(), and draw_menu().
free_board()
void free_board ()
Frees all memory allocated for the animated pieces.
Definition at line 470 of file views.c.
References board, BOARD_SIZE, free_piece(), gameStateFlag, and isWhitesTurn.
free_view()
void free_view ()
Frees all allocated memory of the game sprites.
Definition at line 312 of file views.c.
References bg_base, bg_instructions, bg_play, bg_start, cursor, and free_sprite().
game_set_state()
void game_set_state (enum menu_state_codes state)
Updates the game state to the given state.
Parameters
state new game state to be set
Definition at line 271 of file views.c.
References game_cur_state, and state.
get_cursor_X()
int get_cursor_X ()
Get the cursor X pos.
Returns
int mouse x pos
Definition at line 158 of file views.c.
References cursor, and get_sprite_X().
get_cursor_Y()
int get_cursor_Y ()
Get the cursor Y pos.
Returns
int mouse y pos
Definition at line 162 of file views.c.
References cursor, and get_sprite_Y().
get_kbd_selected_opt()
int get_kbd_selected_opt ()
Get the kbd selected menu option.
Returns
int index of the transition state table
Definition at line 609 of file views.c.
References kbd_selected_opt.
get_mouse_case()
void get_mouse_case (int m_y, int m_x, uint8_t * col, uint8_t * lin)
Gets the mouse current hovering piece/ board square.
Parameters
m_y mouse y cord
m_x mouse x cord
col board hovered col by the mouse
lin board hovered lin by the mouse
Definition at line 91 of file views.c.
References BOARD_SCREEN_CASE_SIZE, and lookUpTable.
get_online_color()
bool get_online_color ()
Get the online color for the current player's turn.
Returns
true is white's turn to play in online mode
false is black's turn to play in online mode
Definition at line 593 of file views.c.
References isWhiteInOnline.
get_piece_at_pos_color()
Piece_Color get_piece_at_pos_color (uint8_t lin, uint8_t col)
Get the piece's color at the given positon on the game board.
Parameters
lin line where to look the color
col collumn where to look the color
Returns
Piece_Color color of the piece in the given pos
Definition at line 597 of file views.c.
References board, and Piece::color.
get_selected_col()
uint8_t get_selected_col ()
Get the selected col in the chess board.
Returns
uint8_t number of the selected col
Definition at line 524 of file views.c.
References select_col.
get_selected_lin()
uint8_t get_selected_lin ()
Get the selected lin in the chess board.
Returns
uint8_t number of the selected lin
Definition at line 527 of file views.c.
References select_lin.
get_selected_valid_moves()
void get_selected_valid_moves (bool arr[8][8])
Get the selected valid moves and returns them in the given matrix.
Parameters
arr matrix where valid moves should be stored
Definition at line 66 of file views.c.
References board, get_valid_moves(), isWhitesTurn, moves, select_col, and select_lin.
is_selected_case()
bool is_selected_case (int lin, int col)
Check if (lin,col) is the selected case.
Parameters
lin Line of the selected case to be set
col Column of the selected case to be set
Returns
true if (lin,col) is the select case
false otherwise
Definition at line 77 of file views.c.
References select_col, and select_lin.
is_valid_move()
bool is_valid_move (int lin, int col)
Checks if moving to (lin,col) is valid.
Parameters
lin Line for the destination position
col Column for the destination position
Returns
true if position is valid
false otherwise
Definition at line 71 of file views.c.
References board, get_valid_moves(), isWhitesTurn, moves, select_col, and select_lin.
mouse_update_pos()
void mouse_update_pos (int x, int y)
Update mouse cords to the given x,y position.
Parameters
x new mouse x cord
y new mouse y cord
Definition at line 151 of file views.c.
References cursor, get_hres(), get_sprite_X(), get_sprite_Y(), get_vres(), set_sprite_X(), and set_sprite_Y().
move_piece()
void move_piece (int lin, int col)
Move selected piece to given cords.
Parameters
lin lin where to move selected piece
col col where to move selected piece
Definition at line 102 of file views.c.
References Blank_space, board, Piece::color, count_exploding, empty_case, exploding_x, exploding_y, GAME_MODE, gameStateFlag, is_inside_board(), isExploding, isWhitesTurn, King, lookUpTable, Piece::p_type, Pawn, select_col, and select_lin.
move_piece_from_to()
void move_piece_from_to (uint8_t i_line, uint8_t i_col, uint8_t f_line, uint8_t final_col)
Moves piece from (i_line,i_col) to (f_line,f_col)
Parameters
i_line Line where piece is located
i_col Column where piece is located
f_line Line where we want the piece to move
final_col Column where we want the piece to move
Definition at line 479 of file views.c.
References Blank_space, board, Piece::color, count_exploding, empty_case, exploding_x, exploding_y, GAME_MODE, gameStateFlag, is_inside_board(), isExploding, isWhitesTurn, King, lookUpTable, Piece::p_type, and Pawn.
set_connected()
void set_connected (bool isconnected)
Set the connected boolean in online gaming.
Parameters
isconnected new value to be set
Definition at line 601 of file views.c.
References hasconnected.
set_kbd_selected_opt()
void set_kbd_selected_opt (bool up)
Move up kbd menu pointed option.
Parameters
up if menu option should be changed
Definition at line 605 of file views.c.
References kbd_selected_opt.
set_online_color()
void set_online_color (bool isWhite)
Set the online color for the current player's turn.
Parameters
isWhite boolean if is white's turn to play
Definition at line 589 of file views.c.
References isWhiteInOnline.
set_selected_case()
void set_selected_case (int lin, int col)
Set the selected case object as (lin,col)
Parameters
lin Line of the selected case to be set
col Column of the selected case to be set
Definition at line 81 of file views.c.
References BOARD_SCREEN_CASE_SIZE, lookUpTable, select_col, and select_lin.
set_up_board()
void set_up_board ()
Allocates all pieces animation sprites and sets their position on the chess board.
Definition at line 320 of file views.c.
References Bishop, BLACK, black_clock, Blank_space, board, create_animSprite(), empty_case, GAME_DURATION, King, Knight, make_piece(), make_sprite(), Pawn, Queen, Rook, WHITE, and white_clock.
set_up_view()
void set_up_view ()
Memory allocation for essential game sprites and positions.
Definition at line 280 of file views.c.
References bg_base, bg_instructions, bg_play, bg_start, buton_back_S, buton_exit_NS, buton_exit_S, buton_instructions_S, buton_multiplayer_S, buton_online_S, buton_play_S, create_animSprite(), cursor, draw_sprite_in_mode_14c(), explosion, explosion_sp, make_sprite(), play_square_select, and set_sprite_pos().
update_timer()
void update_timer (bool white)
Updates the game timer based on RTC second changes.
Parameters
white boolean if white's clock should be updated. False updates Black's clock
Variable Documentation
bg_base
sprite_t* bg_base static
Definition at line 73 of file views.h.
bg_instructions
sprite_t* bg_instructions static
Definition at line 76 of file views.h.
bg_play
sprite_t* bg_play static
Definition at line 75 of file views.h.
bg_start
sprite_t* bg_start static
Definition at line 74 of file views.h.
black_clock
int black_clock = 300 static
Definition at line 119 of file views.h.
board
Board board[8][8] static
Definition at line 123 of file views.h.
buton_back_S
sprite_t* buton_back_S static
Definition at line 79 of file views.h.
buton_exit_NS
sprite_t* buton_exit_NS static
Definition at line 80 of file views.h.
buton_exit_S
sprite_t* buton_exit_S static
Definition at line 81 of file views.h.
buton_instructions_S
sprite_t* buton_instructions_S static
Definition at line 82 of file views.h.
buton_multiplayer_S
sprite_t* buton_multiplayer_S static
Definition at line 83 of file views.h.
buton_online_S
sprite_t* buton_online_S static
Definition at line 84 of file views.h.
buton_play_S
sprite_t* buton_play_S static
Definition at line 85 of file views.h.
cursor
mouse_ptr cursor static
Definition at line 92 of file views.h.
empty_case
Board empty_case static
Definition at line 124 of file views.h.
explosion
AnimSprite* explosion
Definition at line 51 of file views.h.
explosion_sp
sprite_t* explosion_sp
Definition at line 50 of file views.h.
game_cur_state
enum menu_state_codes game_cur_state = menu_entry static
Definition at line 126 of file views.h.
game_exit_sprite
sprite_t* game_exit_sprite static
Definition at line 89 of file views.h.
gameStateFlag
int gameStateFlag = 0 static
Definition at line 112 of file views.h.
hasconnected
bool hasconnected = false static
Definition at line 107 of file views.h.
isWhiteInOnline
bool isWhiteInOnline = true static
Definition at line 106 of file views.h.
isWhitesTurn
bool isWhitesTurn = true static
Definition at line 105 of file views.h.
kbd_selected_opt
int kbd_selected_opt = 0 static
Definition at line 127 of file views.h.
moves
bool moves[8][8] static
Initial value:
= {{0, 0, 0, 0, 0, 0, 0, 0},
                           {0, 0, 0, 0, 0, 0, 0, 0},
                           {0, 0, 0, 0, 0, 0, 0, 0},
                           {0, 0, 0, 0, 0, 0, 0, 0},
                           {0, 0, 0, 0, 0, 0, 0, 0},
                           {0, 0, 0, 0, 0, 0, 0, 0},
                           {0, 0, 0, 0, 0, 0, 0, 0},
                           {0, 0, 0, 0, 0, 0, 0, 0}}
Definition at line 96 of file views.h.
play_square_select
sprite_t* play_square_select static
Definition at line 88 of file views.h.
select_col
uint8_t select_col = 0 static
Definition at line 110 of file views.h.
select_lin
uint8_t select_lin = 0 static
Definition at line 109 of file views.h.
startTime
int startTime static
Definition at line 121 of file views.h.
white_clock
int white_clock = 300 + 1 static
Definition at line 118 of file views.h.